# Generated by Django 4.0.5 on 2022-06-15 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=50)),
                ('documentoDeIdentificacao', models.CharField(max_length=20)),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('cep', models.IntegerField()),
                ('rua', models.CharField(max_length=30)),
                ('localidade', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeEquipamento', models.CharField(choices=[('1', 'Celular'), ('2', 'Tablet'), ('3', 'Computador'), ('4', 'TV'), ('5', 'Asistente Digital'), ('6', 'Celular')], max_length=1)),
                ('numeroDeSerie', models.CharField(max_length=20)),
                ('fabricante', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('data_equipamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ParecerDoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defeitoRelatado', models.CharField(max_length=50)),
                ('diagonosticoEfetuado', models.CharField(max_length=20)),
                ('tempoDeReparo', models.CharField(max_length=30)),
                ('DataDoArquivo', models.CharField(max_length=20)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parecerdotecnico', to='api.equipamento')),
            ],
        ),
    ]
